### PR TITLE
Adding in Burned In Annotation warning (Issue #44)

### LINKED ISSUE #44: Consider warning if Burned In Annotation is YES
If [Burned In Annation](https://dicom.innolitics.com/ciods/cr-image/general-image/00280301) is "YES", our anonymization won't be sufficient.

We could emit a WARN level log message to indicate that there are images with burned-in demographics.

If the attribute is absent, our anonymization still might not be sufficient, so we have to decide what to do about that. I suspect it's often absent, so we might want to take no action.

We could add a flag so users can customize the behaviour. For example
* never warn
* warn if Burned In Annotation is "YES"
* warn unless Burned In Annotation is "NO"

### PR DESCRIPTION
**Pull request by justineclin**
Fixes #44.

Hi Blair,

Super overdue, this is my first Python program and first Git anything. I hope it's not atrocious.

I probably branched at the wrong place. There's a was a rebase conflict and I resolved it somehow, and that may be why the release_notes was a diff even though the content is the same, afaik. I also wasn't too sure to compare to blairconrad/master or embedded-sequence, but my code was based on the latter so that's what I did compared it to.

Thanks so much for reviewing my work!

### CODE REVIEW

**Comment by justineclin** [comment]
Fixes #44

**Review by justineclin — COMMENTED** [review]
The file tests/orig_data/test_burned_in_warning_logged_at_warning/p01_s01_s01_i01.dcm is a shameless copying of one of your test files. Well, this entire feature is a lot of copying of what you've done. So... yeah.

**Comment by blairconrad** [comment]
Hey, @justineclin. Thanks for the contribution. We here at Dicognito Enterprises appreciate it.

As you point out, the content and structure of your pull request do look a little unusual, due to what are probably some irregularities in the branch manipulations. If it suits you, since I'm in no particular rush to release and you're using this partly as a learning exercise (I gather), how about we focus on the mechanics of creating and submitting the pull request. Then we can "repair" your request and focus later on your intended changes.

It's often hard to reconstruct what people have done to their git repository after the fact (usually at work I ask people "what did you do?" and _they_ don't know), but based on your hint "I probably branched from the wrong place" and the state of both the `release_notes.md ` and the commit graph, I'm going to take a guess.

I think you branched from my py39 branch, at some point after I created my own pull request to support Python 3.9, but before I merged it (which delete the branch from GitHub). I will also guess that sometime after you created your branch, I replaced my commit "Support Python 3.9", which altered `release_notes.md` with commit 9f5ec76. Probably I'd made a typo or wanted to reword the message or something.

Then maybe you chose to rebase onto the blairconrad/master branch _after_ the pull request was merged. Or maybe you rebased onto blairconrad/embedded-sequence-delimiter. It would work about the same (like I said, hard to reconstruct the exact sequence of events). At that point, git would see two different versions of `release_notes.md`: one in your branch, which contained my old commit, and one in blairconrad/master, which contained the final commit that altered `release_notes.md`. Then it wanted you to resolve the conflict. You seem to have done so, keeping the new content _except you changed all the line endings from Unix-style to DOS-style_ (see [032e76622107d70b544b57c7476d0419993f2cc2](https://github.com/blairconrad/dicognito/pull/101/commits/032e76622107d70b544b57c7476d0419993f2cc2)).

This is why your pull request ended up with two commits:

```
❯ git log --graph --format=short justin/master

* commit cafe32ed155e1c3d2c51788142fe3197050fa001 (HEAD -> justin-pr, justin/master)
| Author: Justin Lin <justin.ec.lin@gmail.com>
|
|     Added Burned In Annotation warning
|
* commit 032e76622107d70b544b57c7476d0419993f2cc2
| Author: Blair Conrad <blair@blairconrad.com>
|
|     Support Python 3.9
|
* commit 4e7c83309d907423b6d83533fddb2e08e29978c1 (origin/embedded-sequence-delimiter, embedded-sequence-delimiter)
| Author: Blair Conrad <blair@blairconrad.com>
|
|     Require pydicom 2.1 to be able to anonymize datasets with encapsulated pixel data that contains embedded sequence delimiter
|
* commit 438f433cc1dc32a4c28c8ce362cd9f2b9370dc91
| Author: Blair Conrad <blair@blairconrad.com>
|
|     Accept directory parts in load_dcm
|
*   commit 978c06be8b908bb9bbebe562773dfe049fa9307b (origin/master, master)
|\  Merge: 20c6164 9f5ec76
| | Author: Blair Conrad <blair@blairconrad.com>
| |
| |     Merge pull request #99 from blairconrad/py39
```

(which you can also see at https://github.com/blairconrad/dicognito/pull/101/commits, but I recommend becoming comfortable with the command line)

If you hadn't changed the line endings in the file, git would've realized there was no change and dropped the commit entirely (just as the commit was altered not to amend and of the other files from #99, because the content was the same).

There are some other problems with the pull request: 
1. your branch name is master, not some cool name unique to the issue. This is not going to cause any technical problems for me, but can cause problems for future you, as once your pull request is merged, the blairconrad/dicognito master branch will advance (and will do so later on as other issues are fixed), and there will be a difference from your master branch. Technically legal, but confusing
2. you're trying to merge into embedded-sequence-delimiter, not into master

Reviewing your initial comment

> I probably branched at the wrong place. There's a was a rebase conflict and I resolved it somehow, and that may be why the release_notes was a diff even though the content is the same, afaik. I also wasn't too sure to compare to blairconrad/master or embedded-sequence, but my code was based on the latter so that's what I did compared it to.

it seems you had some difficulty and/or confusion along the way. I hope you weren't avoiding reaching out. I'm always happy to help, and answering questions/fixing problems early usually makes things a lot better and is a lot easier than trying to diagnose and repair later. Also, if you have problems, others will as well.

One thing that I wonder about is that the workflow I attempted to reconstruct above deviates at several significant points from that described in this repository's [CONTRIBUTING.md](https://github.com/blairconrad/dicognito/blob/master/CONTRIBUTING.md#making-changes). You're a GitHub novice, so I wouldn't expect you to go hunting through the repository for such a guide (they're a sort of de facto standard though, and many repositories have them), but GitHub usually guides contributors to the file, from the issue and the pull request workflows. Did this not happen? Or was some of the content in the CONTRIBUTING unclear?

I'll let you digest and respond to all that. If you're then still willing, let's continue our conversation.

**Comment by blairconrad** [comment]
Oh, @justineclin! It seems I inadvertently closed this this pull request by deleting my embedded-sequence-delimiter branch (which I guess makes sense, since it was the target of your PR). I did not mean to do so, but it is almost fortuitous, since it highlights the error in the original pull request. We can keep talking through the PR even though it's closed, though. Or we can take all my comments to a separate channel or some sort. Your choice.

**Comment by justineclin** [comment]
Hi @blairconrad! Thanks for the note - fortuitous indeed. Since we're here already, I'm happy to continue using this to chat a bit further. You've some questions I want to at least address and set myself up for the next steps. I trust you don't mind this approach.

Thank you so very much again for putting in the effort to reverse engineer my work and written so detailed an explanation in assisting me seeing my errors. Given my novice status, it will probably take quite a few iterations and quite a bit of searching for me to get my code and process to an acceptable level. I beg your pardon and hope you'll not let instructing me take you away from the rest of your priorities. I am willing and committed to make any/all changes you propose and discuss any ideas you have. Thank you very much again, in advance. 

To your question:

> how about we focus on the mechanics of creating and submitting the pull request. Then we can "repair" your request and focus later on your intended changes.

Yes! Absolutely. I agree with the approach of "process" first, code content second. Happy to iterate until it is right.

Your guess at what I did in branching to arrive at the current state of repo/sandbox is impressive. Sadly, I don't recall the exact sequence in which this occurred, like the rest of the folks you've had to counsel. I was doing a lot of trying things out. I think I tried, to rebase my feature (and possibly master) branch to the latest change, whether it's on the blairconrad/master or otherwise. I recall I did at some point rebase onto the blairconrad/embedded-sequence-delimiter branch. Usually, whenever I see a change notification coming from GitHub, I open GitKraken (GK), see if my branch is behind, and try to rebase onto the latest. I was just trying things out - there wasn't a lot of thinking on it. It might not help, but my GitKraken graph looks like this:

image

> You seem to have done so, keeping the new content except you changed all the line endings from Unix-style to DOS-style (see 032e76622107d70b544b57c7476d0419993f2cc2).

Oh, I was surprised by this. I guess GitKraken must have done this for me. My Preferences → General → AutoCRLF is clear. In Preferences → Editor → End of Line Character, "CRLF" is selected (should it be?).

I should've noticed the ending change since there was no content change in the diff. I'll try to remember this for next time.

> it seems you had some difficulty and/or confusion along the way. I hope you weren't avoiding reaching out.

Thanks so much for your offer to help and asking! I think in general, I should reach out a bit more. That said, in this case I think the major reason for this is to try this out myself. I've a tendency to overthink and ask all possible questions before taking a step and that causes two problems (at least), imo - 1) I don't really know exactly how far my understanding is compared to the "right way" of doing something, and 2) I often lose momentum in the asking. So I'm trying to make some mistakes, then do it over correctly. It's a bit more work, and I don't often have the luxury of taking this approach at work, but I figured I could probably try this out here. Thanks for taking the time to help me out here. Please feel free to skip commenting on something if it's too rough. I'm happy to be told "go read this thing, then redo it".

> (Regarding this repository's CONTRIBUTING.md) but GitHub usually guides contributors to the file, from the issue and the pull request workflows. Did this not happen? Or was some of the content in the CONTRIBUTING unclear?

Thanks for the notes around this. You're correct, I did not notice GitHub's guidance to the file while creating the PR. I did at point read through many of the files in the repo because I had to, so I'm fairly sure I had read/skimmed the file (some of its guidance, like the upstream set up, seemed to have happened in my sandbox) though  I think possibly I was hoping to read the parts of CONTRIBUTING.md that I didn't understand after reading how_to_build.md, and then forgot to.

I think that's actually a good place for me to restart. How about I start by reading CONTRIBUTING and trying to set my repos correctly first? (Thank you also for the note on my using the repo name "master" possibly creating a conflict). If you agree, I'll set up my repos first and confirm with you before I go further. I shall find out how wrong I've been. :)

Thanks so much again, Blair! I'll be in touch!

**Comment by justineclin** [comment]
I forgot to ask. In GitKraken, there's a preference to set up GitFlow, which was mentioned in [CONTRIBUTING.md](https://github.com/blairconrad/dicognito/blob/master/CONTRIBUTING.md). Do you use it or have any recommendation to set this up?

image

**Comment by blairconrad** [comment]
Hi again!

In an order that I felt like:

> In GitKraken, there's a preference to set up GitFlow, which was mentioned in CONTRIBUTING.md. Do you use it or have any recommendation to set this up?

The CONTRIBUTING.md actually talks about [GitHub flow](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/github-flow), not [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/). The latter is a heavier-weight model, which I'm sure has some benefits in larger teams, but we don't use it. FakeItEasy tried using it for a while and we found that for our three-person core team with nearly no backported features/fixes (actually they're frontported in Git Flow), it added only process with no benefits. 

I doubt there's much point in setting it up in GitKraken.


> Thank you also for the note on my using the repo name "master" possibly creating a conflict

nit: I think you mean branch name.

> I recall I did at some point rebase onto the blairconrad/embedded-sequence-delimiter branch

Possibly, but I'm not 100% behind that assessment. You for sure rebased onto py39. I can see it in your graph. embedded-sequence-delimiter was added later, and if you did at one point rebase on top of it, you've since removed those commits.

> Usually, whenever I see a change notification coming from GitHub, I open GitKraken (GK), see if my branch is behind, and try to rebase onto the latest.

The only branch you need to worry about is master. Any other branch would belong to some other topic that someone in the dicognito community has in flight. The maintainers (me) will make sure things are sorted out, but until those other branches are merged into master, they are not "published". They may be interesting, but rarely will they be something you have to build upon. (There are always exceptions, but you'd know when you were in one. Most likely because it would've been discussed beforehand.)

>>you changed all the line endings from Unix-style to DOS-style (see 032e766).

>Oh, I was surprised by this. I guess GitKraken must have done this for me. My Preferences → General → AutoCRLF is clear. In Preferences → Editor → End of Line Character, "CRLF" is selected (should it be?).

I have not used GitKraken in a very long time, and appear not to have it installed anyhow. I tend to only lecture on [how to use the command line tools](https://blairconrad.com/2020/06/04/why-i-teach-git-using-only-the-command-line/) because there are too many git GUIs out there. And many of them do "helpful" things in the background. Perhaps such as this.

The `.gitattributes` file in the repository seems to be set to disable all line ending changes, via the `* -text` line. That was the intent. I see no reason for a version control system to muck with my content. I don't know if GitKraken's AutoCRLF setting would override it. I'd _hope_ not, but what do I know? I expect the Editor setting would apply regardless though, and that any time you edited a file in the GitKraken editor it would apply CRLFs. But I'm just guessing.

>  How about I start by reading CONTRIBUTING and trying to set my repos correctly first?

Sound good.

I don't mean to suck up too many of your cycles here, and I'm not sure if this will ultimately hurt or harm, but it's worth noting that the GitHub Flow model is nearly identical to the Topic/Team portion of the Topic/Team/Master model we've devised for work. (Only you'll have to pretend that dicognito's master branch is like the team branch.) So the documentation we have in the wiki, and in particular my training session, can also help you on your journey.

Take care. TTYL.

**Comment by justineclin** [comment]
Hello!

Sorry I've disappeared for so long. I'm back. :) I did some fixing
according to the CONTRIBUTING.md (though most of the problems were to do
with resetting/undoing my unnecessary conflict resolution that got merged
when rebasing on non-master branches in the first place), and think this
looks better?

[image: image.png]

If you agree, I'll build/test, and continue on the CONTRIBUTING.MD
<https://github.com/blairconrad/dicognito/blob/master/CONTRIBUTING.md#making-changes>
to
build and test it. If that passes, I'll force push and get a Pull Request
going, but that's for later. :)

Oh, I think this whole exercise of getting to know Git really helped me get
a headstart with working with Monorepo, if nothing else, knowing how easy
it is to screw things up and where to look for help. Your training video
was super useful. I doubt I could've learned this (or not without much more
effort) alone. Git is not that easy a transition from SVN. So thank you
there. :)

Enjoy the rest of your weekend!

- Justin

**Comment by justineclin** [comment]
Hello!

Sorry I've disappeared for so long. I'm back. :) I did some fixing
according to the CONTRIBUTING.md (though most of the problems were to do
with resetting/undoing my unnecessary conflict resolution that got merged
when rebasing on non-master branches in the first place), and think this
looks better?

image


If you agree, I'll build/test, and continue on the CONTRIBUTING.MD
<https://github.com/blairconrad/dicognito/blob/master/CONTRIBUTING.md#making-changes>
to
build and test it. If that passes, I'll force push and get a Pull Request
going, but that's for later. :)

Oh, I think this whole exercise of getting to know Git really helped me get
a headstart with working with Monorepo, if nothing else, knowing how easy
it is to screw things up and where to look for help. Your training video
was super useful. I doubt I could've learned this (or not without much more
effort) alone. Git is not that easy a transition from SVN. So thank you
there. :)

Enjoy the rest of your weekend!

- Justin

**Comment by blairconrad** [comment]
Hi. Nice to hear from you again.

 I had to look up `git diff-tree`. I'd never heard of it.
I think your command is doing what I would've thought of as `git show --name-only`. Git really took Perl's motto ("There's more than one way to do it") and ran with it…

Your graph shape looks good. I can't speak to the content of course, not having your commit to look at, but it looks to me like you're heading down the right path. I look forward to further updates.

I'm glad you found the training to be useful. I agree, Subversion to git is an eye-opener, and I initially hated git. But now I enjoy it in a way that I never did Subvertion. Or maybe I felt that way about svn after I left RCS and CVS. But That was a long time ago.

Cheerio!

**Pull request closed without merging**
