### PR TITLE
Remove pydicom reference from tox.ini

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by justineclin** [comment]
Surely you don't need my approval for merging, but I thought to try out the commenting/approving mechanism. Hope you don't mind.

**Comment by blairconrad** [comment]
> I don't know if you had specific approver in mind, but I'm good with this. Guess we only need to specify the pydicom version in the setup files:
> https://github.com/blairconrad/dicognito/pull/92/files
> 
> ... but don't need to specify the version here? I'm good with the change.

I'm actually on the fence about merging this. An alternative is to specify a version.
Without this line, tox will test with whatever module it gets that satisfies `setup.py`. For now, that's going to be pydicom 2.0. At some point I might want test with multiple pydicoms, but for now I think I'm just going to leave things as they are. I wish I'd updated the version when I changed the one in `setup.py`, but it's probably not worth it now.

**Comment by justineclin** [comment]
Okay, sounds good.

**Comment by blairconrad** [comment]
Putting aside for now.

**Pull request closed without merging**
